import { CalendarDays, CloudDrizzle, CloudSun, Cloudy, Command, CommandIcon, Droplets, Eye, Gauge, Navigation, Search, Snowflake, SunDim, SunIcon, Sunset, Thermometer, ThermometerSun, UserRound, Wind } from "lucide-react";

export const Sun = <SunIcon size={15}/>;
export const sun = <SunDim size={15}/>;
export const calender = <CalendarDays size={15}/>;
export const people = <UserRound size={15}/>;
export const thermometer = <Thermometer size={15}/>;
export const droplets = <Droplets size={15}/>;
export const eye = <Eye size={15}/>;
export const gauge = <Gauge size={15}/>;
export const wind = <Wind size={15}/>;
export const sunset = <Sunset size={15}/>;
export const thermo = <ThermometerSun size={15}/>;
export const navigation = <Navigation size={15}/>;
export const cloudy = <Cloudy size={30}/>;
export const snow = <Snowflake size={30}/>;
export const drizzleIcon = <CloudDrizzle size={25}/>;
export const searchIcon = <Search />;
export const commandIcon = <Command size={14}/>;
export const clearSky = <CloudSun size={30}/>;